name: Pinterest Scraper

on:
  workflow_dispatch:
    inputs:
      keyword:
        description: "Keyword to scrape"
        required: true
        default: "air dry clay"
      board:
        description: "Board name"
        required: true
        default: "myboard"
      domain:
        description: "Domain name"
        required: true
        default: "example.com"
      start_date:
        description: "Start date (YYYY-MM-DD)"
        required: true
        default: "2025-08-24"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: |
          python main.py \
            --keyword "${{ github.event.inputs.keyword }}" \
            --board "${{ github.event.inputs.board }}" \
            --domain "${{ github.event.inputs.domain }}" \
            --start_date "${{ github.event.inputs.start_date }}"

      - name: Commit results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add output/*.csv
          git commit -m "update results"
          git push
